version: "3.3"
#
# COMMON ONLY SETTINGS
#

services:
  web:
    image: bcu/bws
    build:
      context: ./bws
      labels:
        - "csic.cnb.bcu.project.name=3DBionotes"
        - "csic.cnb.bcu.app.name=BWS"
        - "csic.cnb.bcu.app.description=3DBionotes-WS API"
    env_file: .env
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"

volumes:
  dbdata: null
