version: "3.9"
# 
# COMMON ONLY SETTINGS
# 

services:
  web:
    image: bcu/bws
    build:
      context: .
      labels:
        - "csic.cnb.bcu.project.name=3DBionotes"
        - "csic.cnb.bcu.app.name=BWS"
        - "csic.cnb.bcu.app.description=3DBionotes-WS API"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
            timeout: 20s
            retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PMA_EXT_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  dbdata: null
