#
# PRODUCTION ONLY SETTINGS
#
services:
  # App container
  web:
    image: ${IMAGE_NAME}-prod
    build:
      dockerfile: Dockerfile-prod
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
        DB_NAME: ${DB_NAME}
        DB_USER_NAME: ${DB_USER_NAME}
        DB_USER_PASSWD: ${DB_USER_PASSWD}
        PMA_EXT_PORT: ${PMA_EXT_PORT}
    environment:
      - DJANGO_SETTINGS_MODULE=bws.settings.production
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${APP_EXT_PORT}:8000"
    deploy:
      restart_policy:
        condition: always
    depends_on:
            db:
                condition: service_healthy
    labels:
        - "csic.cnb.bcu.app.environment=${ENVIRONMENT}"

  pma:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PMA_EXT_PORT}:80"
    depends_on:
            db:
                condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

volumes:
  dbdata: null
