#
# PRODUCTION ONLY SETTINGS
# Override common settings
#

services:
  # App container
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=bws.settings.production
    deploy:
      restart_policy:
        condition: always
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: bash -c "python manage.py runserver 0.0.0.0:8000"

  pma:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PMA_EXT_PORT}:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  dbdata: null
