#name: '3DBionotes_django'
#
# DEVELOPMENT ONLY SETTINGS
#
services:
  # App container
  web:
    container_name: bws-web
    environment:
      - DJANGO_SETTINGS_MODULE=bws.settings.development
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
