#
# COMMON ONLY SETTINGS
#
services:
  # App container
  web:
    env_file: .env
    build:
      context: ./app
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        APP_NAME: ${APP_NAME}
      labels:
        - "csic.cnb.bcu.project.name=${PROJECT_NAME}"
        - "csic.cnb.bcu.app.name=${APP_NAME}"
        - "csic.cnb.bcu.app.description=3DBionotes-WS API"
        - "csic.cnb.bcu.app.maintainer=jr.macias@cnb.csic.es"
    volumes:
      - ${PATH_DATA}:/data
      - ${PATH_TOOLS}:/tools:ro
