#
# COMMON ONLY SETTINGS
#

services:
  # App container
  web:
    image: bcu/bws
    build:
      context: ./bws
      labels:
        - "csic.cnb.bcu.project.name=3DBionotes"
        - "csic.cnb.bcu.app.name=BWS"
        - "csic.cnb.bcu.app.description=3DBionotes-WS API"
    env_file: .env
    ports:
      - "${APP_EXT_PORT}:8000"
    volumes:
      - ./bws:/app
      - ./data:/data
      - ./tools:/tools
