# Generated by Django 3.2.9 on 2022-05-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellentity',
            old_name='ligand',
            new_name='imageData',
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubauthors', to='api.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubauthors', to='api.publication')),
            ],
        ),
    ]
