# Generated by Django 3.2.9 on 2022-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurehcsmodelentity',
            name='imaging_method',
            field=models.CharField(default='', max_length=255),
        ),
    ]
