# Generated by Django 3.2.9 on 2022-05-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellentity',
            name='id',
        ),
        migrations.AlterField(
            model_name='featurehcsmodelentity',
            name='well_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.wellentity'),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='well_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
