# Generated by Django 3.2.9 on 2022-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220527_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandentity',
            name='IUPACInChIkey',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='pubChemCompoundId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
