# Generated by Django 4.0.4 on 2022-04-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220412_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('externalLink', models.CharField(max_length=200)),
                ('queryLink', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('emdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refMaps', to='api.emdbentry')),
            ],
        ),
        migrations.CreateModel(
            name='RefinedModelMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('externalLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RefinedModelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('externalLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='refinedpdbredomodel',
            name='emdbId',
        ),
        migrations.RemoveField(
            model_name='refinedpdbredomodel',
            name='pdbId',
        ),
        migrations.DeleteModel(
            name='RefinedIsoldeRedoModel',
        ),
        migrations.DeleteModel(
            name='RefinedPdbRedoModel',
        ),
        migrations.AddField(
            model_name='refinedmodelmethod',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelsource'),
        ),
        migrations.AddField(
            model_name='refinedmodel',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelmethod'),
        ),
        migrations.AddField(
            model_name='refinedmodel',
            name='pdbId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_refModels', to='api.pdbentry'),
        ),
        migrations.AddField(
            model_name='refinedmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelsource'),
        ),
    ]
