# Generated by Django 3.2.9 on 2022-05-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220412_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHCSModelEntity',
            fields=[
                ('featuremodelentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.featuremodelentity')),
                ('ligand_name', models.CharField(default='', max_length=255)),
                ('iupac_name', models.CharField(default='', max_length=255)),
                ('inchikey', models.CharField(default='', max_length=255)),
                ('smiles', models.CharField(default='', max_length=255)),
                ('broad_id', models.CharField(default='', max_length=255)),
                ('pubchem_cid', models.CharField(default='', max_length=255)),
                ('pubchem_url', models.URLField()),
                ('unichem_url', models.URLField()),
                ('screen_id', models.CharField(default='', max_length=255)),
                ('plate_id', models.CharField(default='', max_length=255)),
                ('well_id', models.CharField(default='', max_length=255)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.organism')),
            ],
            bases=('api.featuremodelentity',),
        ),
        migrations.CreateModel(
            name='WellEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_externalLink', models.URLField()),
                ('images_ids', models.CharField(default='', max_length=255)),
                ('cell_line', models.CharField(default='', max_length=255)),
                ('quality_control', models.CharField(default='', max_length=255)),
                ('percentage_inhibition', models.CharField(default='', max_length=255)),
                ('hit_over_75_activity', models.CharField(default='', max_length=255)),
                ('number_cells', models.CharField(default='', max_length=255)),
                ('phenotype_annotation_level', models.CharField(default='', max_length=255)),
                ('channels', models.CharField(default='', max_length=255)),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.featurehcsmodelentity')),
            ],
        ),
    ]
