# Generated by Django 3.2.9 on 2022-05-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_featurehcsmodelentity_imaging_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurehcsmodelentity',
            old_name='well_id',
            new_name='well',
        ),
        migrations.RemoveField(
            model_name='featurehcsmodelentity',
            name='pubchem_cid',
        ),
        migrations.AddField(
            model_name='featurehcsmodelentity',
            name='ligand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.pdbtoligand'),
            preserve_default=False,
        ),
    ]
