# Generated by Django 3.2.9 on 2022-05-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220518_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurehcsmodelentity',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.publicationauthor'),
            preserve_default=False,
        ),
    ]
