# Generated by Django 3.2.9 on 2022-06-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220527_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellentity',
            name='imageData',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='well', to='api.ligandentity'),
        ),
    ]
