# Generated by Django 4.0.4 on 2022-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refinedmodel_refinedmodelmethod_refinedmodelsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StructureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.hybridmodel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structuretopics', to='api.topic')),
            ],
        ),
    ]
