# Generated by Django 4.0.4 on 2022-04-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refinedmodel_refinedmodelmethod_refinedmodelsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedmodel',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refinedmodel',
            name='emdbId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refMaps', to='api.emdbentry'),
        ),
        migrations.AlterField(
            model_name='refinedmodel',
            name='pdbId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refModels', to='api.pdbentry'),
        ),
        migrations.AlterField(
            model_name='refinedmodelmethod',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refinedmodelmethod',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='refinedmodelsource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refinedmodelsource',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
