# Generated by Django 4.0.4 on 2022-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_refinedmodel_details_alter_refinedmodel_emdbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandentity',
            name='IUPACInChI',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='IUPACInChIkey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='canonicalSMILES',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='isomericSMILES',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='pubChemCompoundId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='systematicNames',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
