# Generated by Django 3.2.9 on 2022-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wellentity_imagedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellentity',
            old_name='imageData',
            new_name='ligand',
        ),
    ]
