# Generated by Django 3.2.9 on 2022-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_idrwellentity_dbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrwellentity',
            name='dbId',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
