# Generated by Django 3.2.9 on 2022-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_imagedata_wellentity_ligand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateentity',
            name='creationDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='dataDoi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='imagingMethod2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='plateCount',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studyentity',
            name='dataDoi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='micromolarConcentration',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
