# Generated by Django 3.2.9 on 2022-08-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220614_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellentity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='details',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='featureType',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='pdbentry',
        ),
        migrations.AddField(
            model_name='studyentity',
            name='details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studyentity',
            name='externalLink',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studyentity',
            name='featureType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyentity_features', to='api.featuretype'),
        ),
        migrations.AddField(
            model_name='studyentity',
            name='pdbentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyentity_features', to='api.pdbentry'),
        ),
        migrations.AlterField(
            model_name='featureregionentity',
            name='pdbentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featureregionentity_features', to='api.pdbentry'),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='externalLink',
            field=models.URLField(),
        ),
    ]
