# Generated by Django 3.2.9 on 2022-05-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_idrwellentity_dbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('creationDate', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('technologyType', models.CharField(default='', max_length=255)),
                ('imagingMethod1', models.CharField(default='', max_length=255)),
                ('imagingMethod2', models.CharField(default='', max_length=255)),
                ('plateCount', models.CharField(default='', max_length=255)),
                ('dataDoi', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('sampleType', models.CharField(default='', max_length=255)),
                ('dataDoi', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyToOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('organismId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyorganisms', to='api.organism')),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyorganisms', to='api.studyentity')),
            ],
        ),
        migrations.CreateModel(
            name='WellEntity',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('externalLink', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=255)),
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('imageLink', models.URLField()),
                ('imageThumbailLink', models.URLField()),
                ('imagesIds', models.CharField(default='', max_length=255)),
                ('micromolarConcentration', models.CharField(default='', max_length=255)),
                ('cellLine', models.CharField(default='', max_length=255)),
                ('qualityControl', models.CharField(default='', max_length=255)),
                ('percentageInhibition', models.CharField(default='', max_length=255)),
                ('hitOver75Activity', models.CharField(default='', max_length=255)),
                ('numbeCells', models.CharField(default='', max_length=255)),
                ('phenotypeAnnotationLevel', models.CharField(default='', max_length=255)),
                ('channels', models.CharField(default='', max_length=255)),
                ('featureType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wellentity_features', to='api.featuretype')),
                ('pdbentry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wellentity_features', to='api.pdbentry')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.pdbtoligand')),
                ('wells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.plateentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FeatureHCSModelEntity',
        ),
        migrations.DeleteModel(
            name='IDRWellEntity',
        ),
        migrations.AddField(
            model_name='studyentity',
            name='organisms',
            field=models.ManyToManyField(through='api.StudyToOrganism', to='api.Organism'),
        ),
        migrations.AddField(
            model_name='studyentity',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.publicationauthor'),
        ),
        migrations.AddField(
            model_name='screenentity',
            name='assays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.studyentity'),
        ),
        migrations.AddField(
            model_name='plateentity',
            name='plates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highContentScreenings', to='api.screenentity'),
        ),
    ]
