# Generated by Django 3.2.9 on 2022-08-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220810_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssayEntity',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('externalLink', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=255)),
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('sampleType', models.CharField(default='', max_length=255)),
                ('dataDoi', models.CharField(blank=True, default='', max_length=255)),
                ('featureType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayentity_features', to='api.featuretype')),
                ('organisms', models.ManyToManyField(to='api.Organism')),
                ('pdbentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayentity_features', to='api.pdbentry')),
                ('publication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='api.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='assay',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.assayentity'),
        ),
        migrations.DeleteModel(
            name='StudyEntity',
        ),
    ]
