# Generated by Django 3.2.9 on 2022-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220525_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytoorganism',
            name='quantity',
        ),
    ]
