# Generated by Django 3.2.9 on 2022-08-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220810_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='PMDId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='featureregionentity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='featureregionentity',
            name='externalLink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organism',
            name='common_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organism',
            name='externalLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_abbrev',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_first',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_last',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AssayEntity',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('externalLink', models.URLField(blank=True, default='')),
                ('details', models.CharField(default='', max_length=255)),
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('assayType', models.CharField(blank=True, default='', max_length=255)),
                ('assayTypeTermAccession', models.CharField(blank=True, default='', max_length=255)),
                ('screenCount', models.IntegerField(blank=True, default='')),
                ('BIAId', models.CharField(blank=True, default='', max_length=255)),
                ('releaseDate', models.DateField(blank=True, default='', max_length=255)),
                ('dataDoi', models.CharField(blank=True, default='', max_length=255)),
                ('featureType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayentity_features', to='api.featuretype')),
                ('organisms', models.ManyToManyField(to='api.Organism')),
                ('pdbentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assayentity_features', to='api.pdbentry')),
                ('publication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assays', to='api.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='assay',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.assayentity'),
        ),
        migrations.DeleteModel(
            name='StudyEntity',
        ),
    ]
