# Generated by Django 3.2.9 on 2022-05-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_studytoorganism_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyentity',
            old_name='study',
            new_name='publication',
        ),
    ]
