# Generated by Django 3.2.9 on 2022-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220816_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayentity',
            name='details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assayentity',
            name='releaseDate',
            field=models.DateField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assayentity',
            name='screenCount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
