# Generated by Django 3.2.9 on 2022-05-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_study_studyentity_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studytoorganism',
            old_name='organismId',
            new_name='organism',
        ),
        migrations.RenameField(
            model_name='studytoorganism',
            old_name='studyId',
            new_name='study',
        ),
        migrations.RemoveField(
            model_name='plateentity',
            name='plates',
        ),
        migrations.RemoveField(
            model_name='screenentity',
            name='assays',
        ),
        migrations.RemoveField(
            model_name='studyentity',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='imageLink',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='well',
        ),
        migrations.RemoveField(
            model_name='wellentity',
            name='wells',
        ),
        migrations.AddField(
            model_name='plateentity',
            name='screen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='api.screenentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenentity',
            name='assay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.studyentity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyentity',
            name='publicationAuthor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='api.publicationauthor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellentity',
            name='ligand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='api.pdbtoligand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellentity',
            name='plate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='api.plateentity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='imagingMethod2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='micromolarConcentration',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
