# Generated by Django 3.2.9 on 2022-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220816_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenentity',
            old_name='imagingMethod1',
            new_name='imagingMethod',
        ),
        migrations.RenameField(
            model_name='screenentity',
            old_name='imagingMethod2',
            new_name='imagingMethodTermAccession',
        ),
        migrations.AddField(
            model_name='screenentity',
            name='sampleType',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='screenentity',
            name='technologyTypeTermAccession',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='screenentity',
            name='typeTermAccession',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='plateCount',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
