# Generated by Django 3.2.9 on 2022-08-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220816_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateentity',
            old_name='creationDate',
            new_name='name',
        ),
    ]
