# Generated by Django 3.2.9 on 2022-08-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_creationdate_plateentity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellentity',
            name='numbeCells',
        ),
        migrations.AddField(
            model_name='wellentity',
            name='cellLineTermAccession',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wellentity',
            name='controlType',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wellentity',
            name='numberCells',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='imagingMethod',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='cellLine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='channels',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='externalLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='hitOver75Activity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='imageThumbailLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='imagesIds',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='ligand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='well', to='api.ligandentity'),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='percentageInhibition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='phenotypeAnnotationLevel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='qualityControl',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
