# Generated by Django 3.2.9 on 2022-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220816_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellentity',
            name='micromolarConcentration',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='numberCells',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='percentageInhibition',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
