# Generated by Django 3.2.9 on 2022-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220816_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligandentity',
            name='SMILES',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ligandentity',
            name='pubChemURL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='IUPACInChIkey',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='altNames',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='externalLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='formula',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='formula_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='imageLink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='ligandType',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ligandentity',
            name='pubChemCompoundId',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
