# Generated by Django 3.2.9 on 2022-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220817_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assayentity',
            name='publication',
        ),
        migrations.AddField(
            model_name='assayentity',
            name='publications',
            field=models.ManyToManyField(to='api.Publication'),
        ),
    ]
