# Generated by Django 3.2.9 on 2022-08-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220823_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='PMDId',
            new_name='PMCId',
        ),
    ]
