# Generated by Django 3.2.9 on 2022-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_pmdid_publication_pmcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenentity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
