# Generated by Django 3.2.9 on 2022-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_screenentity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assayentity',
            name='screenCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='screenentity',
            name='plateCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wellentity',
            name='numberCells',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
