# Generated by Django 4.2.8 on 2025-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMARTentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('evalue', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
