# Generated by Django 4.2.8 on 2025-06-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFAMentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfamid', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
