# Generated by Django 4.2.8 on 2025-06-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_pfamentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsemblAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('transcriptName', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
