# Generated by Django 4.2.8 on 2025-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_ensemblannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='biomutanentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='dbptmentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='dsysmapentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ebifeaturesentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('features_type', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnsemblVariantEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='intrproentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='mobientries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='molprobityentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PDBEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PDBRedoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PhosphoEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='swissvarentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('evalue', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uniprotmappingentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('gene', models.TextField(default=None, null=True)),
                ('transcript', models.TextField(default=None, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('evalue', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='pfamid',
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='proteinID',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
