# Generated by Django 4.2.8 on 2025-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_biomutanentries_dbptmentries_dsysmapentries_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='biomutanentries',
        ),
        migrations.DeleteModel(
            name='dbptmentries',
        ),
        migrations.DeleteModel(
            name='dsysmapentries',
        ),
        migrations.DeleteModel(
            name='ebifeaturesentries',
        ),
        migrations.DeleteModel(
            name='EnsemblVariantEntry',
        ),
        migrations.DeleteModel(
            name='intrproentries',
        ),
        migrations.DeleteModel(
            name='mobientries',
        ),
        migrations.DeleteModel(
            name='molprobityentries',
        ),
        migrations.DeleteModel(
            name='PDBEntry',
        ),
        migrations.DeleteModel(
            name='PDBRedoEntry',
        ),
        migrations.DeleteModel(
            name='PhosphoEntries',
        ),
        migrations.DeleteModel(
            name='swissvarentries',
        ),
        migrations.DeleteModel(
            name='uniprotmappingentries',
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='proteinID',
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='pfamid',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
