# Generated by Django 4.2.8 on 2025-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_delete_biomutanentries_delete_dbptmentries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='biomutanentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='dbptmentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='dsysmapentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ebifeaturesentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('features_type', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnsemblVariantEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='epitope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epitopte_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('description', models.CharField(blank=True, default='', max_length=535, null=True)),
                ('linear_peptide_seq', models.CharField(blank=True, default='', max_length=4000, null=True)),
                ('linear_peptide_modified_seq', models.CharField(blank=True, default='', max_length=4000, null=True)),
                ('linear_peptide_modification', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('non_aa_source_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('disc_source_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('disc_region', models.CharField(blank=True, default='', max_length=4000, null=True)),
                ('disc_modification', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('mc_region', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('mc_mol1_source_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('mc_mol1_modification', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('mc_mol2_source_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('mc_mol2_modification', models.CharField(blank=True, default='', max_length=85, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='epitope_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epitope_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('object_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('source_antigen_accession', models.CharField(blank=True, default='', max_length=85, null=True)),
                ('source_organism_org_id', models.DecimalField(decimal_places=0, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='intrproentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='mobientries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='molprobityentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PdbDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PDBEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PDBRedoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDBID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PhosphoEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='swissvarentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('evalue', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uniprotmappingentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('gene', models.TextField(default=None, null=True)),
                ('transcript', models.TextField(default=None, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('evalue', models.CharField(blank=True, default='1', max_length=20, null=True)),
                ('type', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pfamentity',
            name='pfamid',
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='proteinID',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pfamentity',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
