# Generated by Django 4.2.8 on 2025-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_biomutanentries_dbptmentries_dsysmapentries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('object_id', models.DecimalField(decimal_places=0, max_digits=22, primary_key=True, serialize=False)),
                ('reference_id', models.DecimalField(decimal_places=0, max_digits=22)),
                ('object_type', models.CharField(max_length=200)),
                ('object_sub_type', models.CharField(blank=True, max_length=200, null=True)),
                ('object_description', models.CharField(blank=True, max_length=535, null=True)),
                ('derivative_type', models.CharField(blank=True, max_length=500, null=True)),
                ('organism_id', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('organism2_id', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('region', models.CharField(blank=True, max_length=1000, null=True)),
                ('starting_position', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('ending_position', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('cell_name', models.CharField(blank=True, max_length=85, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=85, null=True)),
                ('tissue_type', models.CharField(blank=True, max_length=85, null=True)),
                ('origin', models.CharField(blank=True, max_length=85, null=True)),
                ('mol1_seq', models.CharField(blank=True, max_length=4000, null=True)),
                ('mol1_modified_seq', models.CharField(blank=True, max_length=4000, null=True)),
                ('mol1_modification', models.CharField(blank=True, max_length=85, null=True)),
                ('mol1_source_id', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('mol2_modified_seq', models.CharField(blank=True, max_length=4000, null=True)),
                ('mol2_modification', models.CharField(blank=True, max_length=85, null=True)),
                ('mol2_source_id', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('mult_chain_mol_name', models.CharField(blank=True, max_length=85, null=True)),
            ],
        ),
    ]
