# Generated by Django 4.2.8 on 2025-07-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epitope',
            old_name='epitopte_id',
            new_name='epitope_id',
        ),
    ]
