# Generated by Django 4.2.8 on 2025-07-23 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_interprodatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entryId', models.CharField(blank=True, default='', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('entryType', models.CharField(blank=True, default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('f_type', models.IntegerField()),
                ('f_category', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fav_icon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sequence', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutationType', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sourceType', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('alternativeSequence', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mutationEffect', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('wildType', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('numberOfViruses', models.IntegerField()),
                ('reportedProtChange', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('genomicPosition', models.IntegerField()),
                ('originalGenomic', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('newGenomic', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('evidenceLevel', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('f_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='annotations.featuretrack')),
            ],
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('trackTypeId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniprotEntry',
            fields=[
                ('accession', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ensemblannotation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ensemblannotation',
            name='start',
        ),
        migrations.RemoveField(
            model_name='ensemblannotation',
            name='transcriptName',
        ),
        migrations.RemoveField(
            model_name='ensemblannotation',
            name='type',
        ),
        migrations.AddField(
            model_name='biomutanentries',
            name='resID',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ensemblannotation',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ensemblannotation',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ensemblannotation',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='Xref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureId', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrefs', to='annotations.trackdata')),
            ],
        ),
        migrations.AddField(
            model_name='featuretrack',
            name='track_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='annotations.tracktype'),
        ),
        migrations.AddField(
            model_name='featuretrack',
            name='uniprot_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='annotations.uniprotentry'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='annotations.entry')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('fileType', models.CharField(blank=True, default='', max_length=12)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='annotations.entry')),
            ],
        ),
        migrations.CreateModel(
            name='AnnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='annotations.anncategory')),
            ],
        ),
    ]
