# Generated by Django 4.2.8 on 2025-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_anncategory_entry_feature_featuretrack_trackdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElmdbData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprotID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('features_type', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
