# Generated by Django 4.2.8 on 2025-06-18 23:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('orcid', models.CharField(blank=True, default='', max_length=25)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmdbEntry',
            fields=[
                ('dbId', models.CharField(default='', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='dbID doesnt comply', regex='^EMD-[0-9]{4,5}$')])),
                ('title', models.CharField(default='', max_length=500)),
                ('emMethod', models.CharField(choices=[('Single Particle', 'Single Particle'), ('Shelical', 'Shelical'), ('Electron Crystallography', 'Electron Crystallography'), ('tomography', 'tomography'), ('subtomogram averaging', 'subtomogram averaging')], default='Single Particle', max_length=25)),
                ('resolution', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Unreleased', max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entryId', models.CharField(blank=True, default='', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('entryType', models.CharField(blank=True, default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('externalLink', models.URLField(blank=True, default='')),
                ('details', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('dataSource', models.CharField(default='', max_length=255)),
                ('externalLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HybridModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hybridmodels', to='api.emdbentry')),
            ],
        ),
        migrations.CreateModel(
            name='LigandEntity',
            fields=[
                ('IUPACInChIkey', models.CharField(default='', max_length=27, primary_key=True, serialize=False)),
                ('dbId', models.CharField(blank=True, max_length=20, null=True)),
                ('pubChemCompoundId', models.CharField(blank=True, max_length=250, null=True)),
                ('ligandType', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('formula_weight', models.FloatField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=2000, null=True)),
                ('altNames', models.CharField(blank=True, max_length=5000, null=True)),
                ('systematicNames', models.CharField(blank=True, max_length=2000, null=True)),
                ('IUPACInChI', models.CharField(blank=True, max_length=2000, null=True)),
                ('isomericSMILES', models.CharField(blank=True, max_length=2000, null=True)),
                ('canonicalSMILES', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('src_method', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mutation', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('altNames', models.CharField(max_length=1024)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NMRTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('verbose_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=900)),
                ('externalLink', models.URLField(blank=True, default='')),
                ('queryLink', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=900)),
                ('externalLink', models.URLField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.ontology')),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('ncbi_taxonomy_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('externalLink', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdbEntry',
            fields=[
                ('dbId', models.CharField(default='', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='dbID doesnt comply', regex='^[0-9][a-zA-Z_0-9]{3}$')])),
                ('title', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=50)),
                ('relDate', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=5000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlateEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('journal_abbrev', models.CharField(blank=True, default='', max_length=255)),
                ('issn', models.CharField(blank=True, default='', max_length=255)),
                ('issue', models.CharField(blank=True, default='', max_length=255)),
                ('volume', models.CharField(blank=True, default='', max_length=255)),
                ('page_first', models.CharField(blank=True, default='', max_length=255)),
                ('page_last', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.CharField(blank=True, default='', max_length=255)),
                ('doi', models.CharField(default='', max_length=255)),
                ('pubMedId', models.CharField(default='', max_length=255)),
                ('PMCId', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RefinedModelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('externalLink', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('exprSystem', models.CharField(default='', max_length=255)),
                ('assembly', models.CharField(default='', max_length=255)),
                ('ass_method', models.CharField(default='', max_length=255)),
                ('ass_details', models.CharField(default='', max_length=255)),
                ('macromolecules', models.CharField(default='', max_length=255)),
                ('uniProts', models.CharField(default='', max_length=255)),
                ('genes', models.CharField(default='', max_length=255)),
                ('bioFunction', models.CharField(default='', max_length=255)),
                ('bioProcess', models.CharField(default='', max_length=255)),
                ('cellComponent', models.CharField(default='', max_length=255)),
                ('domains', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniProtEntry',
            fields=[
                ('dbId', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('externalLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssayEntity',
            fields=[
                ('featuremodelentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.featuremodelentity')),
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('screenCount', models.IntegerField(blank=True, null=True)),
                ('BIAId', models.CharField(blank=True, default='', max_length=255)),
                ('releaseDate', models.DateField(blank=True, max_length=255, null=True)),
                ('dataDoi', models.CharField(blank=True, default='', max_length=255)),
                ('assayTypes', models.ManyToManyField(related_name='type_term_assays', to='api.ontologyterm')),
                ('organisms', models.ManyToManyField(to='api.organism')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.featuremodelentity',),
        ),
        migrations.CreateModel(
            name='WellEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('externalLink', models.URLField(blank=True)),
                ('imageThumbailLink', models.URLField(blank=True)),
                ('imagesIds', models.CharField(blank=True, default='', max_length=255)),
                ('controlType', models.CharField(blank=True, default='', max_length=255)),
                ('qualityControl', models.CharField(blank=True, default='', max_length=255)),
                ('micromolarConcentration', models.FloatField(blank=True, null=True)),
                ('percentageInhibition', models.FloatField(blank=True, null=True)),
                ('hitOver75Activity', models.CharField(blank=True, default='', max_length=255)),
                ('numberCells', models.IntegerField(blank=True, null=True)),
                ('phenotypeAnnotationLevel', models.CharField(blank=True, default='', max_length=255)),
                ('channels', models.CharField(blank=True, default='', max_length=255)),
                ('cellLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_term_wells', to='api.ontologyterm')),
                ('ligand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='well', to='api.ligandentity')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='api.plateentity')),
            ],
        ),
        migrations.CreateModel(
            name='StructureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.hybridmodel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenEntity',
            fields=[
                ('dbId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('sampleType', models.CharField(blank=True, default='', max_length=255)),
                ('plateCount', models.IntegerField(blank=True, null=True)),
                ('dataDoi', models.CharField(blank=True, default='', max_length=255)),
                ('imagingMethods', models.ManyToManyField(related_name='imaging_term_screens', to='api.ontologyterm')),
                ('screenTypes', models.ManyToManyField(related_name='type_term_screens', to='api.ontologyterm')),
                ('technologyTypes', models.ManyToManyField(related_name='technology_term_screens', to='api.ontologyterm')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.assayentity')),
            ],
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PDB-Redo', 'PDB-Redo'), ('Isolde', 'Isolde'), ('RefMac', 'RefMac'), ('Cerex', 'Cerex')], default='PDB-Redo', max_length=25)),
                ('emdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.emdbentry')),
                ('pdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.pdbentry')),
            ],
        ),
        migrations.CreateModel(
            name='RefinedModelMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('externalLink', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelsource')),
            ],
        ),
        migrations.CreateModel(
            name='RefinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('externalLink', models.CharField(blank=True, max_length=255, null=True)),
                ('queryLink', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=5000, null=True)),
                ('emdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refMaps', to='api.emdbentry')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelmethod')),
                ('pdbId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refModels', to='api.pdbentry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refinedmodelsource')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubauthors', to='api.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubauthors', to='api.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(through='api.PublicationAuthor', to='api.author'),
        ),
        migrations.AddField(
            model_name='plateentity',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='api.screenentity'),
        ),
        migrations.CreateModel(
            name='PdbToLigand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbligands', to='api.ligandentity')),
                ('pdbId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbligands', to='api.pdbentry')),
            ],
        ),
        migrations.CreateModel(
            name='PdbToEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(default='', max_length=5)),
                ('pdbx_beg_seq_num', models.IntegerField(blank=True, null=True)),
                ('pdbx_end_seq_num', models.IntegerField(blank=True, null=True)),
                ('db_align_begin', models.IntegerField(blank=True, null=True)),
                ('db_align_end', models.IntegerField(blank=True, null=True)),
                ('seq_align_begin', models.IntegerField(blank=True, null=True)),
                ('seq_align_end', models.IntegerField(blank=True, null=True)),
                ('auth_seq_align_begin', models.IntegerField(blank=True, null=True)),
                ('auth_seq_align_end', models.IntegerField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbentities', to='api.modelentity')),
                ('pdbId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbentities', to='api.pdbentry')),
            ],
        ),
        migrations.CreateModel(
            name='PdbEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.pdbentry')),
                ('refdoc', models.ManyToManyField(to='api.publication')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.sampleentity')),
            ],
        ),
        migrations.CreateModel(
            name='PdbEntryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbmodels', to='api.author')),
                ('pdbId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdbauthors', to='api.pdbentry')),
            ],
        ),
        migrations.AddField(
            model_name='pdbentry',
            name='dbauthors',
            field=models.ManyToManyField(through='api.PdbEntryAuthor', to='api.author'),
        ),
        migrations.AddField(
            model_name='pdbentry',
            name='emdbs',
            field=models.ManyToManyField(through='api.HybridModel', to='api.emdbentry'),
        ),
        migrations.AddField(
            model_name='pdbentry',
            name='entities',
            field=models.ManyToManyField(through='api.PdbToEntity', to='api.modelentity'),
        ),
        migrations.AddField(
            model_name='pdbentry',
            name='ligands',
            field=models.ManyToManyField(through='api.PdbToLigand', to='api.ligandentity'),
        ),
        migrations.CreateModel(
            name='NMRTargetToPoliprotein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetName', models.CharField(default='', max_length=100)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('uniprotentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniprotentities', to='api.uniprotentry')),
            ],
        ),
        migrations.CreateModel(
            name='NMRTargetToModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('model_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmrtargets', to='api.modelentity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelentities', to='api.nmrtarget')),
            ],
        ),
        migrations.AddField(
            model_name='nmrtarget',
            name='uniprot_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nmrtargets', to='api.uniprotentry'),
        ),
        migrations.AddField(
            model_name='modelentity',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelEntities', to='api.organism'),
        ),
        migrations.AddField(
            model_name='modelentity',
            name='uniprotAcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelEntities', to='api.uniprotentry'),
        ),
        migrations.AddField(
            model_name='hybridmodel',
            name='pdbId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hybridmodels', to='api.pdbentry'),
        ),
        migrations.CreateModel(
            name='FeatureRegionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('externalLink', models.URLField(blank=True, default='')),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=list, null=True)),
                ('featureType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.featuretype')),
                ('ligandentity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.ligandentity')),
                ('pdbentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.pdbentry')),
                ('uniprotentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.uniprotentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='featuremodelentity',
            name='featureType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.featuretype'),
        ),
        migrations.AddField(
            model_name='featuremodelentity',
            name='ligandentity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.ligandentity'),
        ),
        migrations.AddField(
            model_name='featuremodelentity',
            name='pdbentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.pdbentry'),
        ),
        migrations.AddField(
            model_name='featuremodelentity',
            name='uniprotentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_features', to='api.uniprotentry'),
        ),
        migrations.AddField(
            model_name='emdbentry',
            name='pdbIds',
            field=models.ManyToManyField(through='api.HybridModel', to='api.pdbentry'),
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('fileType', models.CharField(blank=True, default='', max_length=12)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.entry')),
            ],
        ),
        migrations.AddField(
            model_name='assayentity',
            name='publications',
            field=models.ManyToManyField(to='api.publication'),
        ),
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('relation', models.CharField(blank=True, default='=', max_length=10, null=True)),
                ('value', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pvalue', models.FloatField(blank=True, null=True)),
                ('dataComment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_analyses', to='api.ligandentity')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_term_analyses', to='api.ontologyterm')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_analyses', to='api.assayentity')),
            ],
        ),
    ]
