# Generated by Django 4.2.8 on 2025-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinedmodel',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
